//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.TDE
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class UIGraphicMenuPanel
    {
        
        public const string NAME = "UIGraphicMenuPanel";
        
        [SerializeField()]
        public UIimg UIimg;
        
        [SerializeField()]
        public UIGraphicItem UIGraphicItem;
        
        [SerializeField()]
        public ScrollRect UIGraphicsView;
        
        [SerializeField()]
        public UIGraphicControlContent UIGraphicControlContent;
        
        [SerializeField()]
        public Image TitleImg;
        
        [SerializeField()]
        public Button UILocalEditorButton;
        
        private UIGraphicMenuPanelData mPrivateData = null;
        
        public UIGraphicMenuPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UIGraphicMenuPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            UIimg = null;
            UIGraphicItem = null;
            UIGraphicsView = null;
            UIGraphicControlContent = null;
            TitleImg = null;
            UILocalEditorButton = null;
            mData = null;
        }
    }
}
