//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.TDE
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    using UniRx;
    using global::TDE;

    public class UIGraphicMenuPanelData : QFramework.UIPanelData
    {
        public TSceneData model;
    }
    
    public partial class UIGraphicMenuPanel : QFramework.UIPanel
    {
        public static  Vector2ReactiveProperty TitleImgLocalPos = new Vector2ReactiveProperty();
        public static BoolReactiveProperty TitleImgActive = new BoolReactiveProperty(false);
        public static ReactiveProperty<Sprite> TitleSprite = new ReactiveProperty<Sprite>();

        RectTransform rectGraphicView;

        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as UIGraphicMenuPanelData ?? new UIGraphicMenuPanelData();
            rectGraphicView = UIGraphicsView.transform as RectTransform;
            UIGraphicControlContent.GenerateUIGrrphicsItem(UIGraphicItem,UIimg, rectGraphicView, mData.model);

            //¶©ÔÄtitleImgÏà¹ØÊôÐÔ
            TitleImgLocalPos.Subscribe(TitleImgLocalPosChange);
            TitleImgActive.Subscribe(bo=> { if (bo) TitleImg.Show(); else TitleImg.Hide(); });
            TitleSprite.Subscribe(sprite => TitleImg.sprite = sprite);
        }



        void TitleImgLocalPosChange(Vector2 ve)
        {
            
            TitleImg.LocalPosition(ve);
        }

      

        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
