//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.TDE
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class UIShowPanel
    {
        
        public const string NAME = "UIShowPanel";
        
        [SerializeField()]
        public UILineItem UILineItem;
        
        [SerializeField()]
        public UITextItem UITextItem;
        
        [SerializeField()]
        public UIImageItem UIImageItem;
        
        [SerializeField()]
        public UIImageContent UIImageContent;
        
        private UIShowPanelData mPrivateData = null;
        
        public UIShowPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UIShowPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            UILineItem = null;
            UITextItem = null;
            UIImageItem = null;
            UIImageContent = null;
            mData = null;
        }
    }
}
