//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.TDE
{
    using global::TDE;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public class UITestPanelData : QFramework.UIPanelData
    {
        public ServerData model;
    }
    
    public partial class UITestPanel : QFramework.UIPanel
    {
        
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException ();
        }

        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as UITestPanelData ?? new UITestPanelData();
            Button.onClick.AddListener(
            () => {
              
              UIMgr.OpenPanel<UIServerDatasMenuPanel>(new UIServerDatasMenuPanelData() { T_Model = Global.OnSelectedGraphic.Value, ServerData = mData.model });});

            ButtonError.onClick.AddListener(() => {
                WebSocketMessage message = new WebSocketMessage() { Id = Global.bindDataDict["4"].Value.Id, State = Global.bindDataDict["4"].Value.State, Data = Global.bindDataDict["4"].Value.Data };
                message.State = "ERROR";
                Global.bindDataDict["4"].Value = message;
            });
            ButtonWarningg.onClick.AddListener(() => {
                WebSocketMessage message = new WebSocketMessage() { Id = Global.bindDataDict["4"].Value.Id, State = Global.bindDataDict["4"].Value.State, Data = Global.bindDataDict["4"].Value.Data };
                message.State = "WARNING";
                Global.bindDataDict["4"].Value = message;      
            });
            // NORMAL
            ButtonNormal.onClick.AddListener(() =>
            {
                WebSocketMessage message = new WebSocketMessage() { Id = Global.bindDataDict["4"].Value.Id, State = Global.bindDataDict["4"].Value.State, Data = Global.bindDataDict["4"].Value.Data };
                message.State = "NORMAL";
                Global.bindDataDict["4"].Value = message;
            });
        }

        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
