//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.TDE
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class UITestPanel
    {
        
        public const string NAME = "UITestPanel";
        
        [SerializeField()]
        public UIDataToggle UIDataToggle;
        
        [SerializeField()]
        public Button Button;
        
        [SerializeField()]
        public Button ButtonError;
        
        [SerializeField()]
        public Button ButtonWarningg;
        
        [SerializeField()]
        public Button ButtonNormal;
        
        [SerializeField()]
        public Button ButtonReadScene;
        
        [SerializeField()]
        public Button ButtonUpLoadScene;
        
        [SerializeField()]
        public ScrollRect ScenesScrollView;
        
        [SerializeField()]
        public ToggleGroup Content;
        
        [SerializeField()]
        public Button ScenesScrollButton;
        
        [SerializeField()]
        public Button ScenesScrollCloseButton;
        
        [SerializeField()]
        public Image UIUPloadBG;
        
        [SerializeField()]
        public Text UITextScnenName;
        
        [SerializeField()]
        public InputField UIUPloadInputField;
        
        [SerializeField()]
        public Button UIUPloadButton;
        
        [SerializeField()]
        public Button UIUPloadCloseButton;
        
        private UITestPanelData mPrivateData = null;
        
        public UITestPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UITestPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            UIDataToggle = null;
            Button = null;
            ButtonError = null;
            ButtonWarningg = null;
            ButtonNormal = null;
            ButtonReadScene = null;
            ButtonUpLoadScene = null;
            ScenesScrollView = null;
            Content = null;
            ScenesScrollButton = null;
            ScenesScrollCloseButton = null;
            UIUPloadBG = null;
            UITextScnenName = null;
            UIUPloadInputField = null;
            UIUPloadButton = null;
            UIUPloadCloseButton = null;
            mData = null;
        }
    }
}
