//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Config
    {
        public const string BundleName = "config";
        public const string GRAPHICSMENMCONFIG = "graphicsmenmconfig";
    }
    public class Draw
    {
        public const string BundleName = "draw";
        public const string BG_001 = "bg_001";
        public const string BG_002 = "bg_002";
        public const string BG_003 = "bg_003";
        public const string BG_004 = "bg_004";
        public const string BG_005 = "bg_005";
        public const string BG_006 = "bg_006";
        public const string BG_007 = "bg_007";
        public const string BG_008  = "bg_008 ";
        public const string BG_009 = "bg_009";
        public const string BG_010_TEXT = "bg_010_text";
        public const string BG_011 = "bg_011";
        public const string BG_012 = "bg_012";
        public const string BG_013 = "bg_013";
    }
    public class Face
    {
        public const string BundleName = "face";
        public const string BTN_ARROW_DISABLE = "btn_arrow_disable";
        public const string BTN_ARROW_DOWN = "btn_arrow_down";
        public const string BTN_CLOSE = "btn_close";
        public const string BTN_STYLE1_DISABLED = "btn_style1_disabled";
        public const string BTN_STYLE1_HIGHLIGHTED = "btn_style1_highlighted";
        public const string BTN_STYLE1_NORMAL = "btn_style1_normal";
        public const string BTN_STYLE1_PRESSED = "btn_style1_pressed";
    }
    public class Line
    {
        public const string BundleName = "line";
        public const string ICO_ARROWS = "ico_arrows";
        public const string ICO_BLOOD = "ico_blood";
        public const string ICO_HP = "ico_hp";
        public const string ICO_HP_BG = "ico_hp_bg";
        public const string ICO_MP = "ico_mp";
        public const string ICO_SHAIZI = "ico_shaizi";
        public const string ICO_SKILLBG = "ico_skillbg";
        public const string ICO_SMALLMAPARR = "ico_smallmaparr";
        public const string ICO_STATUS = "ico_status";
        public const string ICO_TONGQIAN = "ico_tongqian";
        public const string ICO_YUANBAO = "ico_yuanbao";
        public const string ICO_YUANBG = "ico_yuanbg";
    }
    public class Test
    {
        public const string BundleName = "test";
        public const string TITLEBG_001 = "titlebg_001";
        public const string TITLEBG_002 = "titlebg_002";
    }
    public class Texture
    {
        public const string BundleName = "texture";
        public const string BEGINARROWS1 = "beginarrows1";
        public const string BEGINLINE1 = "beginline1";
        public const string ENDARROWS1 = "endarrows1";
        public const string ENDLINE1 = "endline1";
        public const string SEGMENT1 = "segment1";
        public const string BEGINARROWS3 = "beginarrows3";
        public const string BEGINLINE3 = "beginline3";
        public const string ENDARROWS3 = "endarrows3";
        public const string ENDLINE3 = "endline3";
        public const string SEGMENT3 = "segment3";
        public const string BEGINARROWS5 = "beginarrows5";
        public const string BEGINLINE5 = "beginline5";
        public const string ENDARROWS5 = "endarrows5";
        public const string ENDLINE5 = "endline5";
        public const string SEGMENT5 = "segment5";
        public const string AIGEI_COM = "aigei_com";
        public const string DIANJISHOUSHI = "dianjishoushi";
        public const string ICON_ADD = "icon_add";
        public const string SHOUZHI = "shouzhi";
        public const string TUOZHUAI = "tuozhuai";
        public const string TUOZHUAI1 = "tuozhuai1";
    }
    public class Uigraphicmenupanel_prefab
    {
        public const string BundleName = "uigraphicmenupanel_prefab";
        public const string UIGRAPHICMENUPANEL = "uigraphicmenupanel";
    }
    public class Uishowpanel_prefab
    {
        public const string BundleName = "uishowpanel_prefab";
        public const string UISHOWPANEL = "uishowpanel";
    }
}
