//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Aigei_com_t
    {
        public const string BundleName = "aigei_com_t";
        public const string AIGEI_COM = "aigei_com";
    }
    public class Config
    {
        public const string BundleName = "config";
        public const string GRAPHICSMENMCONFIG = "graphicsmenmconfig";
        public const string WIDGETCONFIG = "widgetconfig";
        public const string WIDGETPREFABCONFIG = "widgetprefabconfig";
    }
    public class Icon
    {
        public const string BundleName = "icon";
        public const string ARRAW = "arraw";
        public const string BG_010 = "bg_010";
        public const string CIRCLE = "circle";
        public const string 上 = "上";
        public const string 上下居中 = "上下居中";
        public const string 上传 = "上传";
        public const string 上移一层 = "上移一层";
        public const string 下 = "下";
        public const string 下移一层 = "下移一层";
        public const string 两端对齐 = "两端对齐";
        public const string 保存 = "保存";
        public const string 关闭 = "关闭";
        public const string 删除 = "删除";
        public const string 前进一步 = "前进一步";
        public const string 剪切 = "剪切";
        public const string 取消组合 = "取消组合";
        public const string 右对齐 = "右对齐";
        public const string 后退一步 = "后退一步";
        public const string 图元库功能 = "图元库功能";
        public const string 填充颜色 = "填充颜色";
        public const string 复制 = "复制";
        public const string 对齐 = "对齐";
        public const string 居上 = "居上";
        public const string 居下 = "居下";
        public const string 展开 = "展开";
        public const string 左右居中 = "左右居中";
        public const string 左对齐 = "左对齐";
        public const string 帮助 = "帮助";
        public const string 搜索 = "搜索";
        public const string 收起 = "收起";
        public const string 放大比例和添加页码 = "放大比例和添加页码";
        public const string 文字倾斜 = "文字倾斜";
        public const string 文字加粗 = "文字加粗";
        public const string 文字横排 = "文字横排";
        public const string 文字纵向 = "文字纵向";
        public const string 文字颜色 = "文字颜色";
        public const string 更改图元 = "更改图元";
        public const string 最大化 = "最大化";
        public const string 最小化 = "最小化";
        public const string 正常比例 = "正常比例";
        public const string 特殊符号 = "特殊符号";
        public const string 粘贴 = "粘贴";
        public const string 组合 = "组合";
        public const string 缩小比例 = "缩小比例";
        public const string 置于底层 = "置于底层";
        public const string 置于顶层 = "置于顶层";
        public const string 边框颜色 = "边框颜色";
        public const string 还原 = "还原";
        public const string 选择 = "选择";
        public const string 链接数据 = "链接数据";
    }
    public class Image_y
    {
        public const string BundleName = "image_y";
        public const string IMAGE = "image";
        public const string 动力用电 = "动力用电";
        public const string 图元控件 = "图元控件";
        public const string 照明用电 = "照明用电";
        public const string 特殊用电 = "特殊用电";
        public const string 空调用电 = "空调用电";
        public const string 综合用电 = "综合用电";
        public const string 虚表 = "虚表";
    }
    public class Mouse_icon
    {
        public const string BundleName = "mouse_icon";
        public const string DIANJISHOUSHI = "dianjishoushi";
        public const string ICON_ADD = "icon_add";
        public const string SHOUZHI = "shouzhi";
        public const string TUOZHUAI = "tuozhuai";
        public const string TUOZHUAI1 = "tuozhuai1";
    }
    public class Test
    {
        public const string BundleName = "test";
        public const string TITLEBG_001 = "titlebg_001";
        public const string TITLEBG_002 = "titlebg_002";
    }
    public class Texture
    {
        public const string BundleName = "texture";
        public const string BEGINARROWS1 = "beginarrows1";
        public const string BEGINLINE1 = "beginline1";
        public const string ENDARROWS1 = "endarrows1";
        public const string ENDLINE1 = "endline1";
        public const string SEGMENT1 = "segment1";
        public const string BEGINARROWS3 = "beginarrows3";
        public const string BEGINLINE3 = "beginline3";
        public const string ENDARROWS3 = "endarrows3";
        public const string ENDLINE3 = "endline3";
        public const string SEGMENT3 = "segment3";
        public const string BEGINARROWS5 = "beginarrows5";
        public const string BEGINLINE5 = "beginline5";
        public const string ENDARROWS5 = "endarrows5";
        public const string ENDLINE5 = "endline5";
        public const string SEGMENT5 = "segment5";
    }
    public class Uiprefab
    {
        public const string BundleName = "uiprefab";
        public const string UIATTRIBUTEPANEL = "uiattributepanel";
        public const string UICANVASPANEL = "uicanvaspanel";
        public const string UIFUNCTIONPANEL = "uifunctionpanel";
        public const string UIGRAPHICMENUPANEL = "uigraphicmenupanel";
        public const string UIGRAPHICMENUSCROLLVIEWPANEL = "uigraphicmenuscrollviewpanel";
        public const string UILINKEDSERVERPANEL = "uilinkedserverpanel";
        public const string UIOPERATEPANEL = "uioperatepanel";
        public const string UISCENESSCROLLVIEWPANEL = "uiscenesscrollviewpanel";
        public const string UISERVERDATASMENUPANEL = "uiserverdatasmenupanel";
        public const string UISHOWPANEL = "uishowpanel";
        public const string UIUPLOADPANEL = "uiuploadpanel";
        public const string UIWIDGET_ECG = "uiwidget_ecg";
    }
    public class 控件
    {
        public const string BundleName = "控件";
        public const string 电计量控件 = "电计量控件";
    }
}
