//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.TDE
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class UICanvasPanel
    {
        
        public const string NAME = "UICanvasPanel";
        
        [SerializeField()]
        public Button firstPageBtn;
        
        [SerializeField()]
        public Button secondPageBtn;
        
        [SerializeField()]
        public Button allPageBtn;
        
        [SerializeField()]
        public Button newCreatePageBtn;
        
        [SerializeField()]
        public InputField widthInputField;
        
        [SerializeField()]
        public Button widthUpBtn;
        
        [SerializeField()]
        public Button widthDownBtn;
        
        [SerializeField()]
        public InputField heightInputField;
        
        [SerializeField()]
        public Button heighthUpBtn;
        
        [SerializeField()]
        public Button heightDownBtn;
        
        [SerializeField()]
        public Button reduceScaleBtn;
        
        [SerializeField()]
        public Slider scaleSlider;
        
        [SerializeField()]
        public Button enlargeScaleBtn;
        
        [SerializeField()]
        public Text scaleSize;
        
        [SerializeField()]
        public Button normalScaleBtn;
        
        private UICanvasPanelData mPrivateData = null;
        
        public UICanvasPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UICanvasPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            firstPageBtn = null;
            secondPageBtn = null;
            allPageBtn = null;
            newCreatePageBtn = null;
            widthInputField = null;
            widthUpBtn = null;
            widthDownBtn = null;
            heightInputField = null;
            heighthUpBtn = null;
            heightDownBtn = null;
            reduceScaleBtn = null;
            scaleSlider = null;
            enlargeScaleBtn = null;
            scaleSize = null;
            normalScaleBtn = null;
            mData = null;
        }
    }
}
