//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.TDE
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    using BindingsRx.Bindings;
    using global::TDE;
    using UniRx;

    public class UICanvasPanelData : QFramework.UIPanelData
    {
    }
    
    public partial class UICanvasPanel : QFramework.UIPanel
    {
        
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
         
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as UICanvasPanelData ?? new UICanvasPanelData();
            // please add init code here
            Global.currentCanvasheight.Subscribe(f => heightInputField.text = f.ToString());
            Global.currentCanvasWidth.Subscribe(f => widthInputField.text = f.ToString());
            RegisterEvent();
        }

        void RegisterEvent()
        {
            #region вўВи
            //firstPageBtn.onClick.AddListener(() =>
            //{

            //});

            //secondPageBtn.onClick.AddListener(() =>
            //{

            //});

            //allPageBtn.onClick.AddListener(() =>
            //{

            //});

            //newCreatePageBtn.onClick.AddListener(() =>
            //{

            //});

            #endregion

            widthInputField.onEndEdit.AddListener(width =>
            {
              if(Global.currentSceneData.Value.IsNotNull()) Global.currentSceneData.Value.canvasWidth.Value = int.Parse( width);
            });

            widthUpBtn.onClick.AddListener(() =>
            {
                if (Global.currentSceneData.Value.IsNotNull()) Global.currentSceneData.Value.canvasWidth.Value += 1;
            });

            widthDownBtn.onClick.AddListener(() =>
            {
                if (Global.currentSceneData.Value.IsNotNull()) Global.currentSceneData.Value.canvasWidth.Value -= 1;
            });

            heightInputField.onEndEdit.AddListener(height =>
            {
                if (Global.currentSceneData.Value.IsNotNull()) Global.currentSceneData.Value.canvasHeight.Value = int.Parse(height);
            });

            heighthUpBtn.onClick.AddListener(() =>
            {
                if (Global.currentSceneData.Value.IsNotNull()) Global.currentSceneData.Value.canvasHeight.Value += 1;
            });

            heightDownBtn.onClick.AddListener(() =>
            {
                if (Global.currentSceneData.Value.IsNotNull()) Global.currentSceneData.Value.canvasHeight.Value -= 1;
            });

            reduceScaleBtn.onClick.AddListener(() =>
            {

            });


            reduceScaleBtn.onClick.AddListener(() =>
            {

            });


            scaleSlider.onValueChanged.AddListener(value =>
            {

            });

            enlargeScaleBtn.onClick.AddListener(() =>
            {

            });

            
            normalScaleBtn.onClick.AddListener(() =>
            {
                Global.fullScreen.Value = true;
            });


        }
        
        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
