//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.TDE
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class UIFunctionPanel
    {
        
        public const string NAME = "UIFunctionPanel";
        
        [SerializeField()]
        public Button documentBtn;
        
        [SerializeField()]
        public Button editorBtn;
        
        [SerializeField()]
        public Button pelBtn;
        
        [SerializeField()]
        public Button canvasBtn;
        
        [SerializeField()]
        public Button dataBtn;
        
        [SerializeField()]
        public Button viewBtn;
        
        [SerializeField()]
        public Button helpBtn;
        
        [SerializeField()]
        public Button questionBtn;
        
        [SerializeField()]
        public Button minBtn;
        
        [SerializeField()]
        public Button maxBtn;
        
        [SerializeField()]
        public Button quitBtn;
        
        [SerializeField()]
        public Button CloseItemBtn;
        
        [SerializeField()]
        public DocumentItem DocumentItem;
        
        [SerializeField()]
        public EditorItem EditorItem;
        
        [SerializeField()]
        public CanvasItem CanvasItem;
        
        [SerializeField()]
        public DataItem DataItem;
        
        [SerializeField()]
        public ViewItem ViewItem;
        
        [SerializeField()]
        public PelItem PelItem;
        
        [SerializeField()]
        public HelpItem HelpItem;
        
        private UIFunctionPanelData mPrivateData = null;
        
        public UIFunctionPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UIFunctionPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            documentBtn = null;
            editorBtn = null;
            pelBtn = null;
            canvasBtn = null;
            dataBtn = null;
            viewBtn = null;
            helpBtn = null;
            questionBtn = null;
            minBtn = null;
            maxBtn = null;
            quitBtn = null;
            CloseItemBtn = null;
            DocumentItem = null;
            EditorItem = null;
            CanvasItem = null;
            DataItem = null;
            ViewItem = null;
            PelItem = null;
            HelpItem = null;
            mData = null;
        }
    }
}
