//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.TDE
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    using static QFramework.TDE.UIGraphicControlContent;

    public class UIGraphicMenuScrollViewPanelData : QFramework.UIPanelData
    {
       public PrimSet model;
    }
    
    public partial class UIGraphicMenuScrollViewPanel : QFramework.UIPanel
    {
        
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as UIGraphicMenuScrollViewPanelData ?? new UIGraphicMenuScrollViewPanelData();
            // please add init code here
            //确定
            ScenesScrollButton.onClick.AddListener(() => {
                //确认 配置
                foreach (KeyValuePair<string,bool> kv in mData.model.data)
                {
                    mData.model.content.SetUIGraphicItemActive(kv.Key, kv.Value);
                }
               UIManager.Instance.HideUI<UIGraphicMenuScrollViewPanel>();
            });
            //关闭
            ScenesScrollCloseButton.onClick.AddListener(() => UIManager.Instance.HideUI<UIGraphicMenuScrollViewPanel>());

        }

        //初始化
        void PanelOnOpen()
        {
            if (Content.transform.childCount > 0) foreach (Transform item in Content.transform) { Destroy(item.gameObject); }

            if (!(mData.model != null && mData.model.data!=null&& mData.model.data.Count >= 1)) return;
            foreach (KeyValuePair<string,bool> kv in mData.model.data)
            {
                UIGraphicItemToggle item = UIGraphicItemToggle.Instantiate();
                item.ApplySelfTo(self => self.Label.text = kv.Key)
                    .ApplySelfTo(self => { Toggle tog = self.GetComponent<Toggle>(); if (tog)
                        {
                            tog.isOn = kv.Value;
                            tog.onValueChanged.AddListener(bo => mData.model.data[kv.Key] = bo);
                        }})
                    .ApplySelfTo(self =>  self.transform.SetParent(Content.transform, false) )
                    .ApplySelfTo(self => self.Show());
            }
            
        }

        protected override void OnOpen(QFramework.IUIData uiData)
        {
            mData = uiData as UIGraphicMenuScrollViewPanelData ?? new UIGraphicMenuScrollViewPanelData();
            PanelOnOpen();
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
