//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.TDE
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class UIGraphicMenuScrollViewPanel
    {
        
        public const string NAME = "UIGraphicMenuScrollViewPanel";
        
        [SerializeField()]
        public UIGraphicItemToggle UIGraphicItemToggle;
        
        [SerializeField()]
        public ScrollRect ScenesScrollView;
        
        [SerializeField()]
        public ToggleGroup Content;
        
        [SerializeField()]
        public Button ScenesScrollButton;
        
        [SerializeField()]
        public Button ScenesScrollCloseButton;
        
        private UIGraphicMenuScrollViewPanelData mPrivateData = null;
        
        public UIGraphicMenuScrollViewPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UIGraphicMenuScrollViewPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            UIGraphicItemToggle = null;
            ScenesScrollView = null;
            Content = null;
            ScenesScrollButton = null;
            ScenesScrollCloseButton = null;
            mData = null;
        }
    }
}
