//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.TDE
{
    using global::TDE;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public class UILinkedServerPanelData : QFramework.UIPanelData
    {
        public ServerData ServerData;
    }
    
    public partial class UILinkedServerPanel : QFramework.UIPanel
    {
        
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
           
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as UILinkedServerPanelData ?? new UILinkedServerPanelData();
            ConfirmButton.onClick.AddListener(()=>StartCoroutine( ConfirmOnClick()));
            CancelButton.onClick.AddListener(() => { UIManager.Instance.HideUI<UILinkedServerPanel>(); });

            TileButton.onClick.AddListener(() => Tile.Hide());
        }
        
        private IEnumerator ConfirmOnClick()
        {
            if (!InputField.text.IsNullOrEmpty())
            {
                mData.ServerData = new ServerData(InputField.text, () => {
                    Debug.Log("chenggong");
                    UIManager.Instance.HideUI<UILinkedServerPanel>();
                }, () => {
                    Tile.Show();
                });
                yield return StartCoroutine(mData.ServerData.ie);
            }
        }

        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
