//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.TDE
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class UILinkedServerPanel
    {
        
        public const string NAME = "UILinkedServerPanel";
        
        [SerializeField()]
        public InputField InputField;
        
        [SerializeField()]
        public Button ConfirmButton;
        
        [SerializeField()]
        public Button CancelButton;
        
        [SerializeField()]
        public Empty4Raycast Tile;
        
        [SerializeField()]
        public Button TileButton;
        
        [SerializeField()]
        public Text Text;
        
        private UILinkedServerPanelData mPrivateData = null;
        
        public UILinkedServerPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UILinkedServerPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            InputField = null;
            ConfirmButton = null;
            CancelButton = null;
            Tile = null;
            TileButton = null;
            Text = null;
            mData = null;
        }
    }
}
