//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.TDE
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class UIOperatePanel
    {
        
        public const string NAME = "UIOperatePanel";
        
        [SerializeField()]
        public Button CloseItemBtn;
        
        [SerializeField()]
        public Operation Operation;
        
        [SerializeField()]
        public ClipBoard Clipboard;
        
        [SerializeField()]
        public Font Font;
        
        [SerializeField()]
        public Paragraph Paragraph;
        
        [SerializeField()]
        public Tool Tool;
        
        [SerializeField()]
        public ShapeStyle ShapeStyle;
        
        [SerializeField()]
        public Arrange Arrange;
        
        [SerializeField()]
        public ColorItem ColorItem;
        
        private UIOperatePanelData mPrivateData = null;
        
        public UIOperatePanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UIOperatePanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            CloseItemBtn = null;
            Operation = null;
            Clipboard = null;
            Font = null;
            Paragraph = null;
            Tool = null;
            ShapeStyle = null;
            Arrange = null;
            ColorItem = null;
            mData = null;
        }
    }
}
