//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.TDE
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    using UniRx;
    using global::TDE;

    public class UIServerDatasMenuPanelData : QFramework.UIPanelData
    {
       public ServerData ServerData;
    }
    
    public partial class UIServerDatasMenuPanel : QFramework.UIPanel
    {
        public StringReactiveProperty id = new StringReactiveProperty();
        public ReactiveProperty<WebSocketMessage> Message = new ReactiveProperty<WebSocketMessage>();

        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
           
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as UIServerDatasMenuPanelData ?? new UIServerDatasMenuPanelData();

            UIServerDatasCloseButton.GetComponent<Button>().onClick.AddListener(() =>UIManager.Instance.HideUI<UIServerDatasMenuPanel>());

            UIServerDatasContent_Input.Init(mData.ServerData, UIServerDataItem);

            UIServerDatasContent_Input.Message.Subscribe(value =>  Message.Value = value );

            Dropdown uiAsseTypeDropDown= UIAssetTypeDropdown.GetComponent<Dropdown>();
            if (uiAsseTypeDropDown) uiAsseTypeDropDown.onValueChanged.AddListener(i => { UIServerDatasContent_Input.kind = (AssetKindType)i; UIServerDatasContent_Input.InputDataChange(id.Value); });

            Dropdown uiChecktypeDropdown = UIChecktypeDropdown.GetComponent<Dropdown>();
            if (uiChecktypeDropdown) uiChecktypeDropdown.onValueChanged.AddListener(i => { UIServerDatasContent_Input.check= (AssetCheckType)i; UIServerDatasContent_Input.InputDataChange(id.Value); });

            UIServerData_InputField.onEndEdit.AddListener(value=> { if (value.IsNotNull()) id.Value = value; });

            id.Subscribe(value =>  UIServerDatasContent_Input.InputDataChange(value) );

            UIConfirmButton.onClick.AddListener(() => {
                if (Global.OnSelectedGraphic.Value.IsNotNull() && Message.Value.IsNotNull())
                { 
                    Global.OnSelectedGraphic.Value.SetAssetNodeData( new WebSocketMessage() { Id =Message.Value .Id,State= Message.Value .State,Data= Message.Value .Data, Value = Message.Value.Value });
                   UIManager.Instance.HideUI<UIServerDatasMenuPanel>();
                }
            } );
            UIResetutton.onClick.AddListener(() => {
                if (Global.OnSelectedGraphic.Value.IsNotNull())
                {
                    Global.OnSelectedGraphic.Value.ClearAssetNodeData();
                }
            });
            }
        
        protected override void OnOpen(QFramework.IUIData uiData)
        {
            mData = uiData as UIServerDatasMenuPanelData ?? new UIServerDatasMenuPanelData();
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
