//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.TDE
{
    using global::TDE;
    using UniRx;
    using UnityEngine;
    using System.Collections;

    public class UITItem
    {
        public UITextItem UITextItem;
        public UIImageItem UIImageItem;
        public UILineItem UILineItem;
        public UITItem(UITextItem UITextItem, UIImageItem UIImageItem, UILineItem UILineItem)
        {
            this.UIImageItem = UIImageItem;
            this.UITextItem = UITextItem;
            this.UILineItem = UILineItem;
        }
    }

    public class UIShowPanelData : QFramework.UIPanelData
    {
        //new 是为了测试 可以加一些测试数据

       // public TSceneData model=new TSceneData();
    }
    
    public partial class UIShowPanel : QFramework.UIPanel
    {
        UITItem UITItem; 
        RectTransform graphicViewRT;
        Vector2 graphicViewAnchoredPosition, graphicViewSizeDelta;
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
           
        }       
        protected override void OnInit(QFramework.IUIData uiData)
        {
            UITItem = new UITItem(UITextItem, UIImageItem, UILineItem);
            UIContent.Init( UITItem);
            graphicViewRT = GraphicView.transform as RectTransform;
            //  ModelChangeInit(uiData);
            //获取全屏和初始屏 的value
            graphicViewAnchoredPosition = graphicViewRT.anchoredPosition;
            graphicViewSizeDelta = graphicViewRT.sizeDelta;
            RaycastHandle.raycastTarget = false;

            Global.fullScreen.Subscribe(bo => {
                if (bo) { SetFullScreen(); ResetScreenButton.Show(); }
                else { ResetScreen(); ResetScreenButton.Hide(); }
            });
            Global.WebglShowScene.Subscribe(bo => { if (bo) OnShowScene(); else OnEditScene(); });

            ResetScreenButton.onClick.AddListener(() => Global.fullScreen.Value = false);
        }
        
        public IEnumerator ModelChangeInit(TSceneData SceneData)
        {

            //订阅画布大小
            SceneData.canvasWidth.Subscribe(f => { UIContent.SetContentWidth(f); });
            SceneData.canvasHeight.Subscribe(f => { UIContent.SetContentHeight(f); });
            
            IEnumerator ie = UIContent.GenerateGraphicItem(SceneData);
            yield return StartCoroutine(ie);

            //订阅 model添加
            SceneData.ImageDataList.ObserveAdd().Skip(0).Subscribe(item => UIContent.Add(item.Value));
            SceneData.ImageDataList.ObserveRemove().Skip(0).Subscribe(item => UIContent.Remove(item.Value));

            SceneData.LineDataList.ObserveAdd().Skip(0).Subscribe(item =>  UIContent.Add(item.Value));
            SceneData.LineDataList.ObserveRemove().Skip(0).Subscribe(item => UIContent.Remove(item.Value));

            SceneData.TextDataList.ObserveAdd().Skip(0).Subscribe(item => UIContent.Add(item.Value));
            SceneData.TextDataList.ObserveRemove().Skip(0).Subscribe(item => UIContent.Remove(item.Value));

            SceneData.WidgetDataList.ObserveAdd().Skip(0).Subscribe(item =>  UIContent.Add(item.Value));
            SceneData.WidgetDataList.ObserveRemove().Skip(0).Subscribe(item =>  UIContent.Remove(item.Value));
                    
        }

        

        public void OnShowScene()
        {
            SetFullScreen();
            ResetScreenButton.Hide();
            RaycastHandle.raycastTarget = true;
        }
        public void OnEditScene()
        {
            ResetScreen();
            RaycastHandle.raycastTarget = false;
        }

        private void SetFullScreen()
        {
            graphicViewRT.anchoredPosition = Vector2.zero;
            graphicViewRT.sizeDelta = Vector2.zero;
        }
        private void ResetScreen()
        {
            graphicViewRT.anchoredPosition = graphicViewAnchoredPosition;
            graphicViewRT.sizeDelta = graphicViewSizeDelta;
        }

        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
