//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.TDE
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class UIUPloadPanel
    {
        
        public const string NAME = "UIUPloadPanel";
        
        [SerializeField()]
        public Image UIUPloadBG;
        
        [SerializeField()]
        public Text UITextScnenName;
        
        [SerializeField()]
        public InputField UIUPloadInputField;
        
        [SerializeField()]
        public Button UIUPloadButton;
        
        [SerializeField()]
        public Button UIUPloadCloseButton;
        
        private UIUPloadPanelData mPrivateData = null;
        
        public UIUPloadPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UIUPloadPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            UIUPloadBG = null;
            UITextScnenName = null;
            UIUPloadInputField = null;
            UIUPloadButton = null;
            UIUPloadCloseButton = null;
            mData = null;
        }
    }
}
