//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.TDE
{
    using global::TDE;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public class UIUPloadPanelData : QFramework.UIPanelData
    {
        public ServerData model;
    }
    
    public partial class UIUPloadPanel : QFramework.UIPanel
    {
        
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as UIUPloadPanelData ?? new UIUPloadPanelData();

            Init();
            // please add init code here
            //输入事件
            UIUPloadInputField.onValueChanged.AddListener(str => UITextScnenName.text = str);


            //上传 确定事件
            UIUPloadButton.onClick.AddListener(() => StartCoroutine( UIUPloadButtonOnClick()));

            UIUPloadCloseButton.onClick.AddListener(() => UIManager.Instance.HideUI<UIUPloadPanel>());
        }
        
        void Init()
        {
            if (Global.currentSceneData.Value.IsNotNull())
            UITextScnenName.text = Global.currentSceneData.Value.Name;
        }

        IEnumerator UIUPloadButtonOnClick()
        {
            if (!UITextScnenName.text.Trim().IsNullOrEmpty())
            {
                string currenName = UITextScnenName.text.Trim();
                Global.currentSceneData.Value.Name = currenName;
                Global.OnClick(null);
                string json = Global.currentSceneData.Value.Save();
                if (!json.IsNullOrEmpty())
                {
                    WWWForm form = new WWWForm();
                    form.AddField("name", currenName);
                    form.AddField("josnStr", json);
                    // string jsonSer = string.Format("name={0}&josnStr={1}", currenName, json); 
                   yield return StartCoroutine( mData.model.SceneAddOrUpdata(form, (str) => UIManager.Instance.HideUI<UIUPloadPanel>()));
                }
            }
        }


        protected override void OnOpen(QFramework.IUIData uiData)
        {
            Init();
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
